### ISSUE TITLE
Inconsistencies with MCC File Names

### ISSUE THREAD

**Issue by TristanHehnen** [ulfsri/fsri_materials_database#254]
Hi!

There are some inconsistencies with the MCC file names. 

- the 60 K/min cotton felt files are missing the ["R" for the repetition](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Cotton_Felt/MCC)
- the gypsum wall board paper files are missing the experiment conditions, i.e. [heating rate](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Gypsum_Wallboard_Paper/MCC)
- the polyolefin carpet low pile files are missing the experiment conditions, i.e. [heating rate](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Polyolefin_Carpet_Low_Pile/MCC)
- the straw files are missing the ["min" for the heating rate](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Straw/MCC)
- the file names for the bamboo rug [bamboo ](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Bamboo_Rug_Bamboo/MCC) and [fabric ](https://github.com/ulfsri/fsri_materials_database/tree/main/01_Data/Bamboo_Rug_Fabric/MCC) are different than the directory names

Best, 
Tristan

**Comment by mckinnonm** [comment]
Thanks for bringing these to our attention. I've changed the file names, so everything should be consistent now. Please let us know if you see anything else that doesn't make sense or that you think needs to be modified.

**Comment by TristanHehnen** [comment]
Thank you very much!
